# Kyverno Policy для запрета создания Spark-приложения с определенным именем
# Эта политика блокирует создание подов с меткой spark-app-name=pyspark-k8s-client
# ВАЖНО: Применяется с флагом -n для указания namespace
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: deny-spark-app-pyspark-k8s-client
  # namespace будет установлен через kubectl apply -n <namespace>
  annotations:
    policies.kyverno.io/title: "Deny Spark App pyspark-k8s-client"
    policies.kyverno.io/category: "Spark Security"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/subject: "Pod"
    policies.kyverno.io/description: >
      Эта политика запрещает создавать поды
      с меткой spark-app-name=pyspark-k8s-client.
      Используется для временного блокирования конкретного Spark-приложения.
spec:
  validationFailureAction: enforce
  background: true
  
  rules:
    - name: deny-pyspark-k8s-client-pods
      match:
        any:
        - resources:
            kinds:
              - Pod
      
      # Исключаем cleanup Job'ы по метке
      exclude:
        any:
        - resources:
            kinds:
              - Pod
            selector:
              matchLabels:
                job-name: delete-spark-policy-after-15min
        - resources:
            kinds:
              - Pod
            selector:
              matchLabels:
                job-name: cleanup-banned-pods-immediate
        - resources:
            kinds:
              - Pod
            names:
              - "delete-spark-policy-after-15min-*"
              - "cleanup-banned-pods-immediate-*"
      
      validate:
        message: >
          Создание подов с меткой 'spark-app-name=pyspark-k8s-client' 
          временно запрещено.
          Эта политика действует в течение 15 минут.
        pattern:
          metadata:
            =(labels):
              =(spark-app-name): "!pyspark-k8s-client"
---
# ПРИМЕЧАНИЕ: CleanupPolicy удалена, так как требует дополнительных RBAC прав
# Используется только immediate Job для одноразового удаления подов
# Если нужна периодическая проверка, настройте CronJob вместо CleanupPolicy
---
# Job для немедленного удаления существующих подов
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-banned-pods-immediate
  # namespace будет установлен через kubectl apply -n <namespace>
  annotations:
    description: "Немедленно удаляет поды с spark-app-name=pyspark-k8s-client"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    metadata:
      name: cleanup-pods
    spec:
      serviceAccountName: spark-pod-cleaner
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        env:
        # Получаем namespace из downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "[$(date)] Starting immediate cleanup of banned pods..."
          echo "Target namespace: $POD_NAMESPACE"
          echo "Target label: spark-app-name=pyspark-k8s-client"
          echo ""
          
          # Небольшая задержка для инициализации
          sleep 2
          
          # Получаем список подов в текущем namespace
          echo "Searching for pods..."
          PODS=$(kubectl get pods -n "$POD_NAMESPACE" -l spark-app-name=pyspark-k8s-client -o name 2>/dev/null || true)
          
          if [ -z "$PODS" ]; then
            echo "✓ No pods found with the banned label."
            echo "Nothing to clean up."
          else
            echo "✗ Found pods to delete:"
            echo "$PODS" | sed 's/^/  - /'
            echo ""
            
            # Удаляем найденные поды принудительно
            echo "Deleting pods..."
            kubectl delete -n "$POD_NAMESPACE" -l spark-app-name=pyspark-k8s-client pods --grace-period=0 --force 2>&1 | sed 's/^/  /'
            
            echo ""
            echo "✓ Cleanup completed successfully."
          fi
          
          echo "[$(date)] Job finished."
---
# ServiceAccount для Job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-pod-cleaner
  # namespace будет установлен через kubectl apply -n <namespace>
---
# Role с правами на удаление подов
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-pod-cleaner-role
  # namespace будет установлен через kubectl apply -n <namespace>
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-pod-cleaner-binding
  # namespace будет установлен через kubectl apply -n <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-pod-cleaner-role
subjects:
- kind: ServiceAccount
  name: spark-pod-cleaner
  # namespace будет взят из текущего контекста
---
# ПРИМЕЧАНИЕ: Автоматическое удаление политики через 15 минут отключено
# Причина: Job блокируется самой политикой из-за autogen правил Kyverno
# 
# Для удаления политики используйте:
#   kubectl delete policy deny-spark-app-pyspark-k8s-client -n <namespace>
#
# Или установите таймер вручную:
#   sleep 900 && kubectl delete policy deny-spark-app-pyspark-k8s-client -n spark
